### ISSUE TITLE
Script install on a k1 creality error

### ISSUE THREAD

**Issue by Miczach** [Clon1998/mobileraker_companion#101] opened 2024-09-16 19:48 UTC
Hi, any idea, i got this error while trying to install mobileraker:

Checking required system packages are installed...
./mobileraker_companion/scripts/install.sh: line 194: opkg: not found
./mobileraker_companion/scripts/install.sh: line 195: opkg: not found

Thanks

**Comment by Clon1998** [comment] 2024-09-16 19:59
Hey, can you provide me the version of creality OS you are using?
I'll try to reproduce it on my development K1

**Comment by Miczach** [comment] 2024-09-16 20:01
No problem 1.3.3.29.

**Comment by Miczach** [comment] 2024-09-18 21:01
> Hey, can you provide me the version of creality OS you are using? I'll try to reproduce it on my development K1

Have you been hable to reproduce it?
Thanks

**Comment by ElForastero** [comment] 2024-10-07 19:33
Well, I was facing the same issue and opkg indeed wasn't available for some reason.

I did a Factory Reset and installed everything from scratch, now it works, but not really.
 
![image](https://github.com/user-attachments/assets/8b51d389-18a6-4279-9e68-57b8fc39b73f)

**Comment by Clon1998** [comment] 2024-10-08 06:13
Sorry for my late response I bussy else where.

Seems like entware will be removed after updating the machine.


I will verify my code base and adjust it just like in

https://github.com/TheSpaghettiDetective/moonraker-obico/issues/89

**Comment by Clon1998** [comment] 2024-10-11 07:55
@Miczach, Can you run the installer again?
I updated the code to include the path to the `opkg` binary rather than using the command.

@ElForastero I am not sure what was going on with your python installation since the `logging` package should be provided by any full python 3.x installation. Since it is now working, I assume your initial installation got corrupted.

**Comment by Clon1998** [comment] 2024-12-27 16:43
Closed as this seems to be fixed

**Closed by Clon1998** 2024-12-27 16:43 UTC
